// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { XLFileAPI } from './xlfile-api';
import { XLFileDB } from './xlfile-db';

@Injectable({
  providedIn: 'root'
})
export class XLFileService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  XLFileServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private xlfilesUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongxslx/go/v1/xlfiles';

  constructor(
    private http: HttpClient
  ) { }

  /** GET xlfiles from the server */
  getXLFiles(): Observable<XLFileDB[]> {
    return this.http.get<XLFileDB[]>(this.xlfilesUrl)
      .pipe(
        tap(_ => this.log('fetched xlfiles')),
        catchError(this.handleError<XLFileDB[]>('getXLFiles', []))
      );
  }

  /** GET xlfile by id. Will 404 if id not found */
  getXLFile(id: number): Observable<XLFileDB> {
    const url = `${this.xlfilesUrl}/${id}`;
    return this.http.get<XLFileDB>(url).pipe(
      tap(_ => this.log(`fetched xlfile id=${id}`)),
      catchError(this.handleError<XLFileDB>(`getXLFile id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new xlfile to the server */
  postXLFile(xlfiledb: XLFileDB): Observable<XLFileDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    xlfiledb.Sheets = []

		return this.http.post<XLFileDB>(this.xlfilesUrl, xlfiledb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted xlfiledb id=${xlfiledb.ID}`)
			}),
			catchError(this.handleError<XLFileDB>('postXLFile'))
		);
  }

  /** DELETE: delete the xlfiledb from the server */
  deleteXLFile(xlfiledb: XLFileDB | number): Observable<XLFileDB> {
    const id = typeof xlfiledb === 'number' ? xlfiledb : xlfiledb.ID;
    const url = `${this.xlfilesUrl}/${id}`;

    return this.http.delete<XLFileDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted xlfiledb id=${id}`)),
      catchError(this.handleError<XLFileDB>('deleteXLFile'))
    );
  }

  /** PUT: update the xlfiledb on the server */
  updateXLFile(xlfiledb: XLFileDB): Observable<XLFileDB> {
    const id = typeof xlfiledb === 'number' ? xlfiledb : xlfiledb.ID;
    const url = `${this.xlfilesUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    xlfiledb.Sheets = []

    return this.http.put(url, xlfiledb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated xlfiledb id=${xlfiledb.ID}`)
      }),
      catchError(this.handleError<XLFileDB>('updateXLFile'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
