// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { XslxAPI } from './xslx-api';
import { XslxDB } from './xslx-db';

@Injectable({
  providedIn: 'root'
})
export class XslxService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  XslxServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private xslxsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongxslx/go/v1/xslxs';

  constructor(
    private http: HttpClient
  ) { }

  /** GET xslxs from the server */
  getXslxs(): Observable<XslxDB[]> {
    return this.http.get<XslxDB[]>(this.xslxsUrl)
      .pipe(
        tap(_ => this.log('fetched xslxs')),
        catchError(this.handleError<XslxDB[]>('getXslxs', []))
      );
  }

  /** GET xslx by id. Will 404 if id not found */
  getXslx(id: number): Observable<XslxDB> {
    const url = `${this.xslxsUrl}/${id}`;
    return this.http.get<XslxDB>(url).pipe(
      tap(_ => this.log(`fetched xslx id=${id}`)),
      catchError(this.handleError<XslxDB>(`getXslx id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new xslx to the server */
  postXslx(xslxdb: XslxDB): Observable<XslxDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

		return this.http.post<XslxDB>(this.xslxsUrl, xslxdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
				this.log(`posted xslxdb id=${xslxdb.ID}`)
			}),
			catchError(this.handleError<XslxDB>('postXslx'))
		);
  }

  /** DELETE: delete the xslxdb from the server */
  deleteXslx(xslxdb: XslxDB | number): Observable<XslxDB> {
    const id = typeof xslxdb === 'number' ? xslxdb : xslxdb.ID;
    const url = `${this.xslxsUrl}/${id}`;

    return this.http.delete<XslxDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted xslxdb id=${id}`)),
      catchError(this.handleError<XslxDB>('deleteXslx'))
    );
  }

  /** PUT: update the xslxdb on the server */
  updateXslx(xslxdb: XslxDB): Observable<XslxDB> {
    const id = typeof xslxdb === 'number' ? xslxdb : xslxdb.ID;
    const url = `${this.xslxsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)

    return this.http.put(url, xslxdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        this.log(`updated xslxdb id=${xslxdb.ID}`)
      }),
      catchError(this.handleError<XslxDB>('updateXslx'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
