// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { XLSheetDB } from '../xlsheet-db'
import { XLSheetService } from '../xlsheet.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-xlsheetstable',
  templateUrl: './xlsheets-table.component.html',
  styleUrls: ['./xlsheets-table.component.css'],
})
export class XLSheetsTableComponent implements OnInit {

  // used if the component is called as a selection component of XLSheet instances
  selection: SelectionModel<XLSheetDB>;
  initialSelection = new Array<XLSheetDB>();

  // the data source for the table
  xlsheets: XLSheetDB[];
  matTableDataSource: MatTableDataSource<XLSheetDB>


  // front repo, that will be referenced by this.xlsheets
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {

	// enable sorting on all fields (including pointers and reverse pointer)
	this.matTableDataSource.sortingDataAccessor = (xlsheetDB: XLSheetDB, property: string) => {
		switch (property) {
				// insertion point for specific sorting accessor
			case 'Name':
				return xlsheetDB.Name;

			case 'MaxRow':
				return xlsheetDB.MaxRow;

			case 'MaxCol':
				return xlsheetDB.MaxCol;

			case 'NbRows':
				return xlsheetDB.NbRows;

				case 'Sheets':
					return this.frontRepo.XLFiles.get(xlsheetDB.XLFile_SheetsDBID.Int64)?.Name;

				default:
					return XLSheetDB[property];
		}
	}; 

	// enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
	this.matTableDataSource.filterPredicate = (xlsheetDB: XLSheetDB, filter: string) => {

		// filtering is based on finding a lower case filter into a concatenated string
		// the xlsheetDB properties
		let mergedContent = ""

		// insertion point for merging of fields
		mergedContent += xlsheetDB.Name.toLowerCase()
		mergedContent += xlsheetDB.MaxRow.toString()
		mergedContent += xlsheetDB.MaxCol.toString()
		mergedContent += xlsheetDB.NbRows.toString()
		if (xlsheetDB.XLFile_SheetsDBID.Int64 != 0) {
        	mergedContent += this.frontRepo.XLFiles.get(xlsheetDB.XLFile_SheetsDBID.Int64)?.Name.toLowerCase()
    	}


		let isSelected = mergedContent.includes(filter.toLowerCase())
		return isSelected
	};

    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private xlsheetService: XLSheetService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of xlsheet instances
    public dialogRef: MatDialogRef<XLSheetsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.xlsheetService.XLSheetServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getXLSheets()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "MaxRow",
        "MaxCol",
        "NbRows",
        "Sheets",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "MaxRow",
        "MaxCol",
        "NbRows",
        "Sheets",
      ]
      this.selection = new SelectionModel<XLSheetDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getXLSheets()
    this.matTableDataSource = new MatTableDataSource(this.xlsheets)
  }

  getXLSheets(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.xlsheets = this.frontRepo.XLSheets_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.xlsheets.forEach(
            xlsheet => {
              let ID = this.dialogData.ID
              let revPointer = xlsheet[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(xlsheet)
              }
            }
          )
          this.selection = new SelectionModel<XLSheetDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.xlsheets
      }
    )
  }

  // newXLSheet initiate a new xlsheet
  // create a new XLSheet objet
  newXLSheet() {
  }

  deleteXLSheet(xlsheetID: number, xlsheet: XLSheetDB) {
    // list of xlsheets is truncated of xlsheet before the delete
    this.xlsheets = this.xlsheets.filter(h => h !== xlsheet);

    this.xlsheetService.deleteXLSheet(xlsheetID).subscribe(
      xlsheet => {
        this.xlsheetService.XLSheetServiceChanged.next("delete")
      }
    );
  }

  editXLSheet(xlsheetID: number, xlsheet: XLSheetDB) {

  }

  // display xlsheet in router
  displayXLSheetInRouter(xlsheetID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongxlsx_go-" + "xlsheet-display", xlsheetID])
  }

  // set editor outlet
  setEditorRouterOutlet(xlsheetID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongxlsx_go_editor: ["github_com_fullstack_lang_gongxlsx_go-" + "xlsheet-detail", xlsheetID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(xlsheetID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongxlsx_go_presentation: ["github_com_fullstack_lang_gongxlsx_go-" + "xlsheet-presentation", xlsheetID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.xlsheets.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.xlsheets.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<XLSheetDB>()

    // reset all initial selection of xlsheet that belong to xlsheet through Anarrayofb
    this.initialSelection.forEach(
      xlsheet => {
        xlsheet[this.dialogData.ReversePointer].Int64 = 0
        xlsheet[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xlsheet)
      }
    )

    // from selection, set xlsheet that belong to xlsheet through Anarrayofb
    this.selection.selected.forEach(
      xlsheet => {
        let ID = +this.dialogData.ID
        xlsheet[this.dialogData.ReversePointer].Int64 = ID
        xlsheet[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xlsheet)
      }
    )

    // update all xlsheet (only update selection & initial selection)
    toUpdate.forEach(
      xlsheet => {
        this.xlsheetService.updateXLSheet(xlsheet)
          .subscribe(xlsheet => {
            this.xlsheetService.XLSheetServiceChanged.next("update")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
