// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { XLFileDB } from '../xlfile-db'
import { XLFileService } from '../xlfile.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-xlfiles-table',
  templateUrl: './xlfiles-table.component.html',
  styleUrls: ['./xlfiles-table.component.css'],
})
export class XLFilesTableComponent implements OnInit {

  // used if the component is called as a selection component of XLFile instances
  selection: SelectionModel<XLFileDB>;
  initialSelection = new Array<XLFileDB>();

  // the data source for the table
  xlfiles: XLFileDB[];
  matTableDataSource: MatTableDataSource<XLFileDB>


  // front repo, that will be referenced by this.xlfiles
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private xlfileService: XLFileService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of xlfile instances
    public dialogRef: MatDialogRef<XLFilesTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // observable for changes in structs
    this.xlfileService.XLFileServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getXLFiles()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "NbSheets",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "NbSheets",
      ]
      this.selection = new SelectionModel<XLFileDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getXLFiles()
    this.matTableDataSource = new MatTableDataSource(this.xlfiles)
  }

  getXLFiles(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.xlfiles = this.frontRepo.XLFiles_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.xlfiles.forEach(
            xlfile => {
              let ID = this.dialogData.ID
              let revPointer = xlfile[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(xlfile)
              }
            }
          )
          this.selection = new SelectionModel<XLFileDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.xlfiles
      }
    )
  }

  // newXLFile initiate a new xlfile
  // create a new XLFile objet
  newXLFile() {
  }

  deleteXLFile(xlfileID: number, xlfile: XLFileDB) {
    // list of xlfiles is truncated of xlfile before the delete
    this.xlfiles = this.xlfiles.filter(h => h !== xlfile);

    this.xlfileService.deleteXLFile(xlfileID).subscribe(
      xlfile => {
        this.xlfileService.XLFileServiceChanged.next("delete")

        console.log("xlfile deleted")
      }
    );
  }

  editXLFile(xlfileID: number, xlfile: XLFileDB) {

  }

  // display xlfile in router
  displayXLFileInRouter(xlfileID: number) {
    this.router.navigate(["xlfile-display", xlfileID])
  }

  // set editor outlet
  setEditorRouterOutlet(xlfileID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["xlfile-detail", xlfileID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(xlfileID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["xlfile-presentation", xlfileID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.xlfiles.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.xlfiles.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<XLFileDB>()

    // reset all initial selection of xlfile that belong to xlfile through Anarrayofb
    this.initialSelection.forEach(
      xlfile => {
        xlfile[this.dialogData.ReversePointer].Int64 = 0
        xlfile[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xlfile)
      }
    )

    // from selection, set xlfile that belong to xlfile through Anarrayofb
    this.selection.selected.forEach(
      xlfile => {
        console.log("selection ID " + xlfile.ID)
        let ID = +this.dialogData.ID
        xlfile[this.dialogData.ReversePointer].Int64 = ID
        xlfile[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xlfile)
      }
    )

    // update all xlfile (only update selection & initial selection)
    toUpdate.forEach(
      xlfile => {
        this.xlfileService.updateXLFile(xlfile)
          .subscribe(xlfile => {
            this.xlfileService.XLFileServiceChanged.next("update")
            console.log("xlfile saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
