// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { XLRowDB } from '../xlrow-db'
import { XLRowService } from '../xlrow.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-xlrows-table',
  templateUrl: './xlrows-table.component.html',
  styleUrls: ['./xlrows-table.component.css'],
})
export class XLRowsTableComponent implements OnInit {

  // used if the component is called as a selection component of XLRow instances
  selection: SelectionModel<XLRowDB>;
  initialSelection = new Array<XLRowDB>();

  // the data source for the table
  xlrows: XLRowDB[];
  matTableDataSource: MatTableDataSource<XLRowDB>


  // front repo, that will be referenced by this.xlrows
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private xlrowService: XLRowService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of xlrow instances
    public dialogRef: MatDialogRef<XLRowsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
    // this is for routerLink on same component when only queryParameter changes
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };

    // observable for changes in structs
    this.xlrowService.XLRowServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getXLRows()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "RowIndex",
        "NbCols",
        "Rows",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "RowIndex",
        "NbCols",
        "Rows",
      ]
      this.selection = new SelectionModel<XLRowDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getXLRows()
    this.matTableDataSource = new MatTableDataSource(this.xlrows)
  }

  getXLRows(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.xlrows = this.frontRepo.XLRows_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.xlrows.forEach(
            xlrow => {
              let ID = this.dialogData.ID
              let revPointer = xlrow[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(xlrow)
              }
            }
          )
          this.selection = new SelectionModel<XLRowDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.xlrows
      }
    )
  }

  // newXLRow initiate a new xlrow
  // create a new XLRow objet
  newXLRow() {
  }

  deleteXLRow(xlrowID: number, xlrow: XLRowDB) {
    // list of xlrows is truncated of xlrow before the delete
    this.xlrows = this.xlrows.filter(h => h !== xlrow);

    this.xlrowService.deleteXLRow(xlrowID).subscribe(
      xlrow => {
        this.xlrowService.XLRowServiceChanged.next("delete")

        console.log("xlrow deleted")
      }
    );
  }

  editXLRow(xlrowID: number, xlrow: XLRowDB) {

  }

  // display xlrow in router
  displayXLRowInRouter(xlrowID: number) {
    this.router.navigate(["xlrow-display", xlrowID])
  }

  // set editor outlet
  setEditorRouterOutlet(xlrowID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["xlrow-detail", xlrowID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(xlrowID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["xlrow-presentation", xlrowID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.xlrows.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.xlrows.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<XLRowDB>()

    // reset all initial selection of xlrow that belong to xlrow through Anarrayofb
    this.initialSelection.forEach(
      xlrow => {
        xlrow[this.dialogData.ReversePointer].Int64 = 0
        xlrow[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xlrow)
      }
    )

    // from selection, set xlrow that belong to xlrow through Anarrayofb
    this.selection.selected.forEach(
      xlrow => {
        console.log("selection ID " + xlrow.ID)
        let ID = +this.dialogData.ID
        xlrow[this.dialogData.ReversePointer].Int64 = ID
        xlrow[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xlrow)
      }
    )

    // update all xlrow (only update selection & initial selection)
    toUpdate.forEach(
      xlrow => {
        this.xlrowService.updateXLRow(xlrow)
          .subscribe(xlrow => {
            this.xlrowService.XLRowServiceChanged.next("update")
            console.log("xlrow saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
