// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { XslxDB } from '../xslx-db'
import { XslxService } from '../xslx.service'

import { FrontRepoService, FrontRepo, NullInt64 } from '../front-repo.service'
@Component({
  selector: 'lib-xslx-sorting',
  templateUrl: './xslx-sorting.component.html',
  styleUrls: ['./xslx-sorting.component.css']
})
export class XslxSortingComponent implements OnInit {

  frontRepo: FrontRepo

  // array of Xslx instances that are in the association
  associatedXslxs = new Array<XslxDB>();

  constructor(
    private xslxService: XslxService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of xslx instances
    public dialogRef: MatDialogRef<XslxSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getXslxs()
  }

  getXslxs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let xslx of this.frontRepo.Xslxs_array) {
          let ID = this.dialogData.ID
          let revPointerID = xslx[this.dialogData.ReversePointer]
          let revPointerID_Index = xslx[this.dialogData.ReversePointer+"_Index"]
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedXslxs.push(xslx)
          }
        }

        // sort associated xslx according to order
        this.associatedXslxs.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer+"_Index"]
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer+"_Index"]
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }  
          }
          return 0;
        });

        console.log("front repo pull returned")
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedXslxs, event.previousIndex, event.currentIndex);

    // set the order of Xslx instances
    let index = 0
    
    for (let xslx of this.associatedXslxs) {
      let revPointerID_Index = xslx[this.dialogData.ReversePointer+"_Index"]
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
    console.log("after drop")
  }

  save() {

    this.associatedXslxs.forEach(
      xslx => {
        this.xslxService.updateXslx(xslx)
          .subscribe(xslx => {
            this.xslxService.XslxServiceChanged.next("update")
            console.log("xslx saved")
          });
      }
    )

    this.dialogRef.close('Sorting of '+ this.dialogData.ReversePointer+' done');
  }
}
