// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { Router, RouterState } from '@angular/router';
import { XslxDB } from '../xslx-db'
import { XslxService } from '../xslx.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'

// generated table component
@Component({
  selector: 'app-xslxs-table',
  templateUrl: './xslxs-table.component.html',
  styleUrls: ['./xslxs-table.component.css'],
})
export class XslxsTableComponent implements OnInit {

  // used if the component is called as a selection component of Xslx instances
  selection: SelectionModel<XslxDB>;
  initialSelection = new Array<XslxDB>();

  // the data source for the table
  xslxs: XslxDB[];
  matTableDataSource: MatTableDataSource<XslxDB>


  // front repo, that will be referenced by this.xslxs
  frontRepo: FrontRepo

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort) sort: MatSort;
  @ViewChild(MatPaginator) paginator: MatPaginator;

  ngAfterViewInit() {
    this.matTableDataSource.sort = this.sort;
    this.matTableDataSource.paginator = this.paginator;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private xslxService: XslxService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of xslx instances
    public dialogRef: MatDialogRef<XslxsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    // https://stackoverflow.com/questions/54627478/angular-7-routing-to-same-component-but-different-param-not-working
    // this is for routerLink on same component when only queryParameter changes
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };

    // observable for changes in structs
    this.xslxService.XslxServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getXslxs()
        }
      }
    )
    if (dialogData == undefined) {
      this.displayedColumns = ['ID', 'Edit', 'Delete', // insertion point for columns to display
        "Name",
        "NbSheets",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "NbSheets",
      ]
      this.selection = new SelectionModel<XslxDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    this.getXslxs()
    this.matTableDataSource = new MatTableDataSource(this.xslxs)
  }

  getXslxs(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo
        console.log("front repo pull returned")

        this.xslxs = this.frontRepo.Xslxs_array;

        // insertion point for variables Recoveries

        // in case the component is called as a selection component
        if (this.dialogData != undefined) {
          this.xslxs.forEach(
            xslx => {
              let ID = this.dialogData.ID
              let revPointer = xslx[this.dialogData.ReversePointer]
              if (revPointer.Int64 == ID) {
                this.initialSelection.push(xslx)
              }
            }
          )
          this.selection = new SelectionModel<XslxDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.xslxs
      }
    )
  }

  // newXslx initiate a new xslx
  // create a new Xslx objet
  newXslx() {
  }

  deleteXslx(xslxID: number, xslx: XslxDB) {
    // list of xslxs is truncated of xslx before the delete
    this.xslxs = this.xslxs.filter(h => h !== xslx);

    this.xslxService.deleteXslx(xslxID).subscribe(
      xslx => {
        this.xslxService.XslxServiceChanged.next("delete")

        console.log("xslx deleted")
      }
    );
  }

  editXslx(xslxID: number, xslx: XslxDB) {

  }

  // display xslx in router
  displayXslxInRouter(xslxID: number) {
    this.router.navigate(["xslx-display", xslxID])
  }

  // set editor outlet
  setEditorRouterOutlet(xslxID: number) {
    this.router.navigate([{
      outlets: {
        editor: ["xslx-detail", xslxID]
      }
    }]);
  }

  // set presentation outlet
  setPresentationRouterOutlet(xslxID: number) {
    this.router.navigate([{
      outlets: {
        presentation: ["xslx-presentation", xslxID]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.xslxs.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.xslxs.forEach(row => this.selection.select(row));
  }

  save() {

    let toUpdate = new Set<XslxDB>()

    // reset all initial selection of xslx that belong to xslx through Anarrayofb
    this.initialSelection.forEach(
      xslx => {
        xslx[this.dialogData.ReversePointer].Int64 = 0
        xslx[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xslx)
      }
    )

    // from selection, set xslx that belong to xslx through Anarrayofb
    this.selection.selected.forEach(
      xslx => {
        console.log("selection ID " + xslx.ID)
        let ID = +this.dialogData.ID
        xslx[this.dialogData.ReversePointer].Int64 = ID
        xslx[this.dialogData.ReversePointer].Valid = true
        toUpdate.add(xslx)
      }
    )

    // update all xslx (only update selection & initial selection)
    toUpdate.forEach(
      xslx => {
        this.xslxService.updateXslx(xslx)
          .subscribe(xslx => {
            this.xslxService.XslxServiceChanged.next("update")
            console.log("xslx saved")
          });
      }
    )
    this.dialogRef.close('Pizza!');
  }
}
