// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongxlsx/go/models"
	"github.com/fullstack-lang/gongxlsx/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __XLCell__dummysDeclaration__ models.XLCell
var __XLCell_time__dummyDeclaration time.Duration

// An XLCellID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getXLCell updateXLCell deleteXLCell
type XLCellID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// XLCellInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postXLCell updateXLCell
type XLCellInput struct {
	// The XLCell to submit or modify
	// in: body
	XLCell *orm.XLCellAPI
}

// GetXLCells
//
// swagger:route GET /xlcells xlcells getXLCells
//
// # Get all xlcells
//
// Responses:
// default: genericError
//
//	200: xlcellDBResponse
func GetXLCells(c *gin.Context) {
	db := orm.BackRepo.BackRepoXLCell.GetDB()

	// source slice
	var xlcellDBs []orm.XLCellDB

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GONG__StackPath", stackParam)
		}
	}

	query := db.Find(&xlcellDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	xlcellAPIs := make([]orm.XLCellAPI, 0)

	// for each xlcell, update fields from the database nullable fields
	for idx := range xlcellDBs {
		xlcellDB := &xlcellDBs[idx]
		_ = xlcellDB
		var xlcellAPI orm.XLCellAPI

		// insertion point for updating fields
		xlcellAPI.ID = xlcellDB.ID
		xlcellDB.CopyBasicFieldsToXLCell(&xlcellAPI.XLCell)
		xlcellAPI.XLCellPointersEnconding = xlcellDB.XLCellPointersEnconding
		xlcellAPIs = append(xlcellAPIs, xlcellAPI)
	}

	c.JSON(http.StatusOK, xlcellAPIs)
}

// PostXLCell
//
// swagger:route POST /xlcells xlcells postXLCell
//
// Creates a xlcell
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostXLCell(c *gin.Context) {

	// Validate input
	var input orm.XLCellAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create xlcell
	xlcellDB := orm.XLCellDB{}
	xlcellDB.XLCellPointersEnconding = input.XLCellPointersEnconding
	xlcellDB.CopyBasicFieldsFromXLCell(&input.XLCell)

	db := orm.BackRepo.BackRepoXLCell.GetDB()
	query := db.Create(&xlcellDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoXLCell.CheckoutPhaseOneInstance(&xlcellDB)
	xlcell := (*orm.BackRepo.BackRepoXLCell.Map_XLCellDBID_XLCellPtr)[xlcellDB.ID]

	if xlcell != nil {
		models.AfterCreateFromFront(&models.Stage, xlcell)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, xlcellDB)
}

// GetXLCell
//
// swagger:route GET /xlcells/{ID} xlcells getXLCell
//
// Gets the details for a xlcell.
//
// Responses:
// default: genericError
//
//	200: xlcellDBResponse
func GetXLCell(c *gin.Context) {

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["stack"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GET params", stackParam)
		}
	}

	db := orm.BackRepo.BackRepoXLCell.GetDB()

	// Get xlcellDB in DB
	var xlcellDB orm.XLCellDB
	if err := db.First(&xlcellDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var xlcellAPI orm.XLCellAPI
	xlcellAPI.ID = xlcellDB.ID
	xlcellAPI.XLCellPointersEnconding = xlcellDB.XLCellPointersEnconding
	xlcellDB.CopyBasicFieldsToXLCell(&xlcellAPI.XLCell)

	c.JSON(http.StatusOK, xlcellAPI)
}

// UpdateXLCell
//
// swagger:route PATCH /xlcells/{ID} xlcells updateXLCell
//
// # Update a xlcell
//
// Responses:
// default: genericError
//
//	200: xlcellDBResponse
func UpdateXLCell(c *gin.Context) {

	// Validate input
	var input orm.XLCellAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db := orm.BackRepo.BackRepoXLCell.GetDB()

	// Get model if exist
	var xlcellDB orm.XLCellDB

	// fetch the xlcell
	query := db.First(&xlcellDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	xlcellDB.CopyBasicFieldsFromXLCell(&input.XLCell)
	xlcellDB.XLCellPointersEnconding = input.XLCellPointersEnconding

	query = db.Model(&xlcellDB).Updates(xlcellDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	xlcellNew := new(models.XLCell)
	xlcellDB.CopyBasicFieldsToXLCell(xlcellNew)

	// get stage instance from DB instance, and call callback function
	xlcellOld := (*orm.BackRepo.BackRepoXLCell.Map_XLCellDBID_XLCellPtr)[xlcellDB.ID]
	if xlcellOld != nil {
		models.AfterUpdateFromFront(&models.Stage, xlcellOld, xlcellNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the xlcellDB
	c.JSON(http.StatusOK, xlcellDB)
}

// DeleteXLCell
//
// swagger:route DELETE /xlcells/{ID} xlcells deleteXLCell
//
// # Delete a xlcell
//
// default: genericError
//
//	200: xlcellDBResponse
func DeleteXLCell(c *gin.Context) {
	db := orm.BackRepo.BackRepoXLCell.GetDB()

	// Get model if exist
	var xlcellDB orm.XLCellDB
	if err := db.First(&xlcellDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&xlcellDB)

	// get an instance (not staged) from DB instance, and call callback function
	xlcellDeleted := new(models.XLCell)
	xlcellDB.CopyBasicFieldsToXLCell(xlcellDeleted)

	// get stage instance from DB instance, and call callback function
	xlcellStaged := (*orm.BackRepo.BackRepoXLCell.Map_XLCellDBID_XLCellPtr)[xlcellDB.ID]
	if xlcellStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, xlcellStaged, xlcellDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
