// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"net/http"
	"time"

	"github.com/fullstack-lang/gongxlsx/go/models"
	"github.com/fullstack-lang/gongxlsx/go/orm"

	"github.com/gin-gonic/gin"
	"github.com/jinzhu/gorm"
)

// declaration in order to justify use of the models import
var __XLFile__dummysDeclaration__ models.XLFile
var __XLFile_time__dummyDeclaration time.Duration

// An XLFileID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getXLFile updateXLFile deleteXLFile
type XLFileID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// XLFileInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postXLFile updateXLFile
type XLFileInput struct {
	// The XLFile to submit or modify
	// in: body
	XLFile *orm.XLFileAPI
}

// GetXLFiles
//
// swagger:route GET /xlfiles xlfiles getXLFiles
//
// Get all xlfiles
//
// Responses:
//    default: genericError
//        200: xlfileDBsResponse
func GetXLFiles(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	var xlfiles []orm.XLFileDB
	query := db.Find(&xlfiles)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// for each xlfile, update fields from the database nullable fields
	for idx := range xlfiles {
		xlfile := &xlfiles[idx]
		_ = xlfile
		// insertion point for updating fields
		if xlfile.Name_Data.Valid {
			xlfile.Name = xlfile.Name_Data.String
		}

		if xlfile.NbSheets_Data.Valid {
			xlfile.NbSheets = int(xlfile.NbSheets_Data.Int64)
		}

	}

	c.JSON(http.StatusOK, xlfiles)
}

// PostXLFile
//
// swagger:route POST /xlfiles xlfiles postXLFile
//
// Creates a xlfile
//     Consumes:
//     - application/json
//
//     Produces:
//     - application/json
//
//     Responses:
//       200: xlfileDBResponse
func PostXLFile(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Validate input
	var input orm.XLFileAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create xlfile
	xlfileDB := orm.XLFileDB{}
	xlfileDB.XLFileAPI = input
	// insertion point for nullable field set
	xlfileDB.Name_Data.String = input.Name
	xlfileDB.Name_Data.Valid = true

	xlfileDB.NbSheets_Data.Int64 = int64(input.NbSheets)
	xlfileDB.NbSheets_Data.Valid = true

	query := db.Create(&xlfileDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, xlfileDB)
}

// GetXLFile
//
// swagger:route GET /xlfiles/{ID} xlfiles getXLFile
//
// Gets the details for a xlfile.
//
// Responses:
//    default: genericError
//        200: xlfileDBResponse
func GetXLFile(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get xlfile in DB
	var xlfile orm.XLFileDB
	if err := db.First(&xlfile, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// insertion point for fields value set from nullable fields
	if xlfile.Name_Data.Valid {
		xlfile.Name = xlfile.Name_Data.String
	}

	if xlfile.NbSheets_Data.Valid {
		xlfile.NbSheets = int(xlfile.NbSheets_Data.Int64)
	}

	c.JSON(http.StatusOK, xlfile)
}

// UpdateXLFile
//
// swagger:route PATCH /xlfiles/{ID} xlfiles updateXLFile
//
// Update a xlfile
//
// Responses:
//    default: genericError
//        200: xlfileDBResponse
func UpdateXLFile(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var xlfileDB orm.XLFileDB

	// fetch the xlfile
	query := db.First(&xlfileDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Validate input
	var input orm.XLFileAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	// update
	// insertion point for nullable field set
	input.Name_Data.String = input.Name
	input.Name_Data.Valid = true

	input.NbSheets_Data.Int64 = int64(input.NbSheets)
	input.NbSheets_Data.Valid = true

	query = db.Model(&xlfileDB).Updates(input)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	// return status OK with the marshalling of the the xlfileDB
	c.JSON(http.StatusOK, xlfileDB)
}

// DeleteXLFile
//
// swagger:route DELETE /xlfiles/{ID} xlfiles deleteXLFile
//
// Delete a xlfile
//
// Responses:
//    default: genericError
func DeleteXLFile(c *gin.Context) {
	db := c.MustGet("db").(*gorm.DB)

	// Get model if exist
	var xlfileDB orm.XLFileDB
	if err := db.First(&xlfileDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&xlfileDB)

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementCommitNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
