// generated by stacks/gong/go/models/controller_file.go
package controllers

import (
	"log"
	"net/http"
	"time"

	"github.com/fullstack-lang/gongxlsx/go/models"
	"github.com/fullstack-lang/gongxlsx/go/orm"

	"github.com/gin-gonic/gin"
)

// declaration in order to justify use of the models import
var __XLRow__dummysDeclaration__ models.XLRow
var __XLRow_time__dummyDeclaration time.Duration

// An XLRowID parameter model.
//
// This is used for operations that want the ID of an order in the path
// swagger:parameters getXLRow updateXLRow deleteXLRow
type XLRowID struct {
	// The ID of the order
	//
	// in: path
	// required: true
	ID int64
}

// XLRowInput is a schema that can validate the user’s
// input to prevent us from getting invalid data
// swagger:parameters postXLRow updateXLRow
type XLRowInput struct {
	// The XLRow to submit or modify
	// in: body
	XLRow *orm.XLRowAPI
}

// GetXLRows
//
// swagger:route GET /xlrows xlrows getXLRows
//
// # Get all xlrows
//
// Responses:
// default: genericError
//
//	200: xlrowDBResponse
func GetXLRows(c *gin.Context) {
	db := orm.BackRepo.BackRepoXLRow.GetDB()

	// source slice
	var xlrowDBs []orm.XLRowDB

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["GONG__StackPath"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GONG__StackPath", stackParam)
		}
	}

	query := db.Find(&xlrowDBs)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// slice that will be transmitted to the front
	xlrowAPIs := make([]orm.XLRowAPI, 0)

	// for each xlrow, update fields from the database nullable fields
	for idx := range xlrowDBs {
		xlrowDB := &xlrowDBs[idx]
		_ = xlrowDB
		var xlrowAPI orm.XLRowAPI

		// insertion point for updating fields
		xlrowAPI.ID = xlrowDB.ID
		xlrowDB.CopyBasicFieldsToXLRow(&xlrowAPI.XLRow)
		xlrowAPI.XLRowPointersEnconding = xlrowDB.XLRowPointersEnconding
		xlrowAPIs = append(xlrowAPIs, xlrowAPI)
	}

	c.JSON(http.StatusOK, xlrowAPIs)
}

// PostXLRow
//
// swagger:route POST /xlrows xlrows postXLRow
//
// Creates a xlrow
//
//	Consumes:
//	- application/json
//
//	Produces:
//	- application/json
//
//	Responses:
//	  200: nodeDBResponse
func PostXLRow(c *gin.Context) {

	// Validate input
	var input orm.XLRowAPI

	err := c.ShouldBindJSON(&input)
	if err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// Create xlrow
	xlrowDB := orm.XLRowDB{}
	xlrowDB.XLRowPointersEnconding = input.XLRowPointersEnconding
	xlrowDB.CopyBasicFieldsFromXLRow(&input.XLRow)

	db := orm.BackRepo.BackRepoXLRow.GetDB()
	query := db.Create(&xlrowDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	orm.BackRepo.BackRepoXLRow.CheckoutPhaseOneInstance(&xlrowDB)
	xlrow := (*orm.BackRepo.BackRepoXLRow.Map_XLRowDBID_XLRowPtr)[xlrowDB.ID]

	if xlrow != nil {
		models.AfterCreateFromFront(&models.Stage, xlrow)
	}

	// a POST is equivalent to a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, xlrowDB)
}

// GetXLRow
//
// swagger:route GET /xlrows/{ID} xlrows getXLRow
//
// Gets the details for a xlrow.
//
// Responses:
// default: genericError
//
//	200: xlrowDBResponse
func GetXLRow(c *gin.Context) {

	// type Values map[string][]string
	values := c.Request.URL.Query()
	if len(values) == 1 {
		value := values["stack"]
		if len(value) == 1 {
			// we have a single parameter
			// we assume it is the stack
			stackParam := value[0]
			log.Println("GET params", stackParam)
		}
	}

	db := orm.BackRepo.BackRepoXLRow.GetDB()

	// Get xlrowDB in DB
	var xlrowDB orm.XLRowDB
	if err := db.First(&xlrowDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	var xlrowAPI orm.XLRowAPI
	xlrowAPI.ID = xlrowDB.ID
	xlrowAPI.XLRowPointersEnconding = xlrowDB.XLRowPointersEnconding
	xlrowDB.CopyBasicFieldsToXLRow(&xlrowAPI.XLRow)

	c.JSON(http.StatusOK, xlrowAPI)
}

// UpdateXLRow
//
// swagger:route PATCH /xlrows/{ID} xlrows updateXLRow
//
// # Update a xlrow
//
// Responses:
// default: genericError
//
//	200: xlrowDBResponse
func UpdateXLRow(c *gin.Context) {

	// Validate input
	var input orm.XLRowAPI
	if err := c.ShouldBindJSON(&input); err != nil {
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db := orm.BackRepo.BackRepoXLRow.GetDB()

	// Get model if exist
	var xlrowDB orm.XLRowDB

	// fetch the xlrow
	query := db.First(&xlrowDB, c.Param("id"))

	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// update
	xlrowDB.CopyBasicFieldsFromXLRow(&input.XLRow)
	xlrowDB.XLRowPointersEnconding = input.XLRowPointersEnconding

	query = db.Model(&xlrowDB).Updates(xlrowDB)
	if query.Error != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = query.Error.Error()
		log.Println(query.Error.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// get an instance (not staged) from DB instance, and call callback function
	xlrowNew := new(models.XLRow)
	xlrowDB.CopyBasicFieldsToXLRow(xlrowNew)

	// get stage instance from DB instance, and call callback function
	xlrowOld := (*orm.BackRepo.BackRepoXLRow.Map_XLRowDBID_XLRowPtr)[xlrowDB.ID]
	if xlrowOld != nil {
		models.AfterUpdateFromFront(&models.Stage, xlrowOld, xlrowNew)
	}

	// an UPDATE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	// in some cases, with the marshalling of the stage, this operation might
	// generates a checkout
	orm.BackRepo.IncrementPushFromFrontNb()

	// return status OK with the marshalling of the the xlrowDB
	c.JSON(http.StatusOK, xlrowDB)
}

// DeleteXLRow
//
// swagger:route DELETE /xlrows/{ID} xlrows deleteXLRow
//
// # Delete a xlrow
//
// default: genericError
//
//	200: xlrowDBResponse
func DeleteXLRow(c *gin.Context) {
	db := orm.BackRepo.BackRepoXLRow.GetDB()

	// Get model if exist
	var xlrowDB orm.XLRowDB
	if err := db.First(&xlrowDB, c.Param("id")).Error; err != nil {
		var returnError GenericError
		returnError.Body.Code = http.StatusBadRequest
		returnError.Body.Message = err.Error()
		log.Println(err.Error())
		c.JSON(http.StatusBadRequest, returnError.Body)
		return
	}

	// with gorm.Model field, default delete is a soft delete. Unscoped() force delete
	db.Unscoped().Delete(&xlrowDB)

	// get an instance (not staged) from DB instance, and call callback function
	xlrowDeleted := new(models.XLRow)
	xlrowDB.CopyBasicFieldsToXLRow(xlrowDeleted)

	// get stage instance from DB instance, and call callback function
	xlrowStaged := (*orm.BackRepo.BackRepoXLRow.Map_XLRowDBID_XLRowPtr)[xlrowDB.ID]
	if xlrowStaged != nil {
		models.AfterDeleteFromFront(&models.Stage, xlrowStaged, xlrowDeleted)
	}

	// a DELETE generates a back repo commit increase
	// (this will be improved with implementation of unit of work design pattern)
	orm.BackRepo.IncrementPushFromFrontNb()

	c.JSON(http.StatusOK, gin.H{"data": true})
}
