// generated by genORMTranslation.go
package orm

import (
	"bufio"
	"bytes"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"

	"gorm.io/gorm"

	"github.com/fullstack-lang/gongxlsx/go/models"

	"github.com/tealeg/xlsx/v3"
)

// BackRepoStruct supports callback functions
type BackRepoStruct struct {
	// insertion point for per struct back repo declarations
	BackRepoXLCell BackRepoXLCellStruct

	BackRepoXLFile BackRepoXLFileStruct

	BackRepoXLRow BackRepoXLRowStruct

	BackRepoXLSheet BackRepoXLSheetStruct

	CommitFromBackNb uint // this ng is updated at the BackRepo level but also at the BackRepo<GongStruct> level

	PushFromFrontNb uint // records increments from push from front
}

func (backRepo *BackRepoStruct) GetLastCommitFromBackNb() uint {
	return backRepo.CommitFromBackNb
}

func (backRepo *BackRepoStruct) GetLastPushFromFrontNb() uint {
	return backRepo.PushFromFrontNb
}

func (backRepo *BackRepoStruct) IncrementCommitFromBackNb() uint {
	if models.Stage.OnInitCommitCallback != nil {
		models.Stage.OnInitCommitCallback.BeforeCommit(&models.Stage)
	}
	if models.Stage.OnInitCommitFromBackCallback != nil {
		models.Stage.OnInitCommitFromBackCallback.BeforeCommit(&models.Stage)
	}
	backRepo.CommitFromBackNb = backRepo.CommitFromBackNb + 1
	return backRepo.CommitFromBackNb
}

func (backRepo *BackRepoStruct) IncrementPushFromFrontNb() uint {
	if models.Stage.OnInitCommitCallback != nil {
		models.Stage.OnInitCommitCallback.BeforeCommit(&models.Stage)
	}
	if models.Stage.OnInitCommitFromFrontCallback != nil {
		models.Stage.OnInitCommitFromFrontCallback.BeforeCommit(&models.Stage)
	}
	backRepo.PushFromFrontNb = backRepo.PushFromFrontNb + 1
	return backRepo.CommitFromBackNb
}

// Init the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) init(db *gorm.DB) {
	// insertion point for per struct back repo declarations
	backRepo.BackRepoXLCell.Init(db)
	backRepo.BackRepoXLFile.Init(db)
	backRepo.BackRepoXLRow.Init(db)
	backRepo.BackRepoXLSheet.Init(db)

	models.Stage.BackRepo = backRepo
}

// Commit the BackRepoStruct inner variables and link to the database
func (backRepo *BackRepoStruct) Commit(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoXLCell.CommitPhaseOne(stage)
	backRepo.BackRepoXLFile.CommitPhaseOne(stage)
	backRepo.BackRepoXLRow.CommitPhaseOne(stage)
	backRepo.BackRepoXLSheet.CommitPhaseOne(stage)

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoXLCell.CommitPhaseTwo(backRepo)
	backRepo.BackRepoXLFile.CommitPhaseTwo(backRepo)
	backRepo.BackRepoXLRow.CommitPhaseTwo(backRepo)
	backRepo.BackRepoXLSheet.CommitPhaseTwo(backRepo)

	backRepo.IncrementCommitFromBackNb()
}

// Checkout the database into the stage
func (backRepo *BackRepoStruct) Checkout(stage *models.StageStruct) {
	// insertion point for per struct back repo phase one commit
	backRepo.BackRepoXLCell.CheckoutPhaseOne()
	backRepo.BackRepoXLFile.CheckoutPhaseOne()
	backRepo.BackRepoXLRow.CheckoutPhaseOne()
	backRepo.BackRepoXLSheet.CheckoutPhaseOne()

	// insertion point for per struct back repo phase two commit
	backRepo.BackRepoXLCell.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoXLFile.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoXLRow.CheckoutPhaseTwo(backRepo)
	backRepo.BackRepoXLSheet.CheckoutPhaseTwo(backRepo)
}

var BackRepo BackRepoStruct

func GetLastCommitFromBackNb() uint {
	return BackRepo.GetLastCommitFromBackNb()
}

func GetLastPushFromFrontNb() uint {
	return BackRepo.GetLastPushFromFrontNb()
}

// Backup the BackRepoStruct
func (backRepo *BackRepoStruct) Backup(stage *models.StageStruct, dirPath string) {
	os.MkdirAll(dirPath, os.ModePerm)

	// insertion point for per struct backup
	backRepo.BackRepoXLCell.Backup(dirPath)
	backRepo.BackRepoXLFile.Backup(dirPath)
	backRepo.BackRepoXLRow.Backup(dirPath)
	backRepo.BackRepoXLSheet.Backup(dirPath)
}

// Backup in XL the BackRepoStruct
func (backRepo *BackRepoStruct) BackupXL(stage *models.StageStruct, dirPath string) {
	os.MkdirAll(dirPath, os.ModePerm)

	// open an existing file
	file := xlsx.NewFile()

	// insertion point for per struct backup
	backRepo.BackRepoXLCell.BackupXL(file)
	backRepo.BackRepoXLFile.BackupXL(file)
	backRepo.BackRepoXLRow.BackupXL(file)
	backRepo.BackRepoXLSheet.BackupXL(file)

	var b bytes.Buffer
	writer := bufio.NewWriter(&b)
	file.Write(writer)
	theBytes := b.Bytes()

	filename := filepath.Join(dirPath, "bckp.xlsx")
	err := ioutil.WriteFile(filename, theBytes, 0644)
	if err != nil {
		log.Panic("Cannot write the XL file", err.Error())
	}
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) Restore(stage *models.StageStruct, dirPath string) {
	models.Stage.Commit()
	models.Stage.Reset()
	models.Stage.Checkout()

	//
	// restauration first phase (create DB instance with new IDs)
	//

	// insertion point for per struct backup
	backRepo.BackRepoXLCell.RestorePhaseOne(dirPath)
	backRepo.BackRepoXLFile.RestorePhaseOne(dirPath)
	backRepo.BackRepoXLRow.RestorePhaseOne(dirPath)
	backRepo.BackRepoXLSheet.RestorePhaseOne(dirPath)

	//
	// restauration second phase (reindex pointers with the new ID)
	//

	// insertion point for per struct backup
	backRepo.BackRepoXLCell.RestorePhaseTwo()
	backRepo.BackRepoXLFile.RestorePhaseTwo()
	backRepo.BackRepoXLRow.RestorePhaseTwo()
	backRepo.BackRepoXLSheet.RestorePhaseTwo()

	models.Stage.Checkout()
}

// Restore the database into the back repo
func (backRepo *BackRepoStruct) RestoreXL(stage *models.StageStruct, dirPath string) {

	// clean the stage
	models.Stage.Reset()

	// commit the cleaned stage
	models.Stage.Commit()

	// open an existing file
	filename := filepath.Join(dirPath, "bckp.xlsx")
	file, err := xlsx.OpenFile(filename)

	if err != nil {
		log.Panic("Cannot read the XL file", err.Error())
	}

	//
	// restauration first phase (create DB instance with new IDs)
	//

	// insertion point for per struct backup
	backRepo.BackRepoXLCell.RestoreXLPhaseOne(file)
	backRepo.BackRepoXLFile.RestoreXLPhaseOne(file)
	backRepo.BackRepoXLRow.RestoreXLPhaseOne(file)
	backRepo.BackRepoXLSheet.RestoreXLPhaseOne(file)

	// commit the restored stage
	models.Stage.Commit()
}
