// generated by gong
import { Component, OnInit, AfterViewInit, ViewChild, Inject, Optional, Input } from '@angular/core';
import { BehaviorSubject } from 'rxjs'
import { MatSort } from '@angular/material/sort';
import { MatPaginator } from '@angular/material/paginator';
import { MatTableDataSource } from '@angular/material/table';
import { MatButton } from '@angular/material/button'

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData, FrontRepoService, FrontRepo, SelectionMode } from '../front-repo.service'
import { NullInt64 } from '../null-int64'
import { SelectionModel } from '@angular/cdk/collections';

const allowMultiSelect = true;

import { ActivatedRoute, Router, RouterState } from '@angular/router';
import { DisplaySelectionDB } from '../displayselection-db'
import { DisplaySelectionService } from '../displayselection.service'

// insertion point for additional imports

// TableComponent is initilizaed from different routes
// TableComponentMode detail different cases 
enum TableComponentMode {
  DISPLAY_MODE,
  ONE_MANY_ASSOCIATION_MODE,
  MANY_MANY_ASSOCIATION_MODE,
}

// generated table component
@Component({
  selector: 'app-displayselectionstable',
  templateUrl: './displayselections-table.component.html',
  styleUrls: ['./displayselections-table.component.css'],
})
export class DisplaySelectionsTableComponent implements OnInit {

  @Input() GONG__StackPath: string = ""

  // mode at invocation
  mode: TableComponentMode = TableComponentMode.DISPLAY_MODE

  // used if the component is called as a selection component of DisplaySelection instances
  selection: SelectionModel<DisplaySelectionDB> = new (SelectionModel)
  initialSelection = new Array<DisplaySelectionDB>()

  // the data source for the table
  displayselections: DisplaySelectionDB[] = []
  matTableDataSource: MatTableDataSource<DisplaySelectionDB> = new (MatTableDataSource)

  // front repo, that will be referenced by this.displayselections
  frontRepo: FrontRepo = new (FrontRepo)

  // displayedColumns is referenced by the MatTable component for specify what columns
  // have to be displayed and in what order
  displayedColumns: string[];

  // for sorting & pagination
  @ViewChild(MatSort)
  sort: MatSort | undefined
  @ViewChild(MatPaginator)
  paginator: MatPaginator | undefined;

  ngAfterViewInit() {

    // enable sorting on all fields (including pointers and reverse pointer)
    this.matTableDataSource.sortingDataAccessor = (displayselectionDB: DisplaySelectionDB, property: string) => {
      switch (property) {
        case 'ID':
          return displayselectionDB.ID

        // insertion point for specific sorting accessor
        case 'Name':
          return displayselectionDB.Name;

        case 'XLFile':
          return (displayselectionDB.XLFile ? displayselectionDB.XLFile.Name : '');

        case 'XLSheet':
          return (displayselectionDB.XLSheet ? displayselectionDB.XLSheet.Name : '');

        default:
          console.assert(false, "Unknown field")
          return "";
      }
    };

    // enable filtering on all fields (including pointers and reverse pointer, which is not done by default)
    this.matTableDataSource.filterPredicate = (displayselectionDB: DisplaySelectionDB, filter: string) => {

      // filtering is based on finding a lower case filter into a concatenated string
      // the displayselectionDB properties
      let mergedContent = ""

      // insertion point for merging of fields
      mergedContent += displayselectionDB.Name.toLowerCase()
      if (displayselectionDB.XLFile) {
        mergedContent += displayselectionDB.XLFile.Name.toLowerCase()
      }
      if (displayselectionDB.XLSheet) {
        mergedContent += displayselectionDB.XLSheet.Name.toLowerCase()
      }

      let isSelected = mergedContent.includes(filter.toLowerCase())
      return isSelected
    };

    this.matTableDataSource.sort = this.sort!
    this.matTableDataSource.paginator = this.paginator!
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.matTableDataSource.filter = filterValue.trim().toLowerCase();
  }

  constructor(
    private displayselectionService: DisplaySelectionService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of displayselection instances
    public dialogRef: MatDialogRef<DisplaySelectionsTableComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
    private activatedRoute: ActivatedRoute,
  ) {

    // compute mode
    if (dialogData == undefined) {
      this.mode = TableComponentMode.DISPLAY_MODE
    } else {
      this.GONG__StackPath = dialogData.GONG__StackPath
      switch (dialogData.SelectionMode) {
        case SelectionMode.ONE_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.ONE_MANY_ASSOCIATION_MODE
          break
        case SelectionMode.MANY_MANY_ASSOCIATION_MODE:
          this.mode = TableComponentMode.MANY_MANY_ASSOCIATION_MODE
          break
        default:
      }
    }

    // observable for changes in structs
    this.displayselectionService.DisplaySelectionServiceChanged.subscribe(
      message => {
        if (message == "post" || message == "update" || message == "delete") {
          this.getDisplaySelections()
        }
      }
    )
    if (this.mode == TableComponentMode.DISPLAY_MODE) {
      this.displayedColumns = ['ID', 'Delete', // insertion point for columns to display
        "Name",
        "XLFile",
        "XLSheet",
      ]
    } else {
      this.displayedColumns = ['select', 'ID', // insertion point for columns to display
        "Name",
        "XLFile",
        "XLSheet",
      ]
      this.selection = new SelectionModel<DisplaySelectionDB>(allowMultiSelect, this.initialSelection);
    }

  }

  ngOnInit(): void {
    let stackPath = this.activatedRoute.snapshot.paramMap.get('GONG__StackPath')
    if (stackPath != undefined) {
      this.GONG__StackPath = stackPath
    }

    this.getDisplaySelections()

    this.matTableDataSource = new MatTableDataSource(this.displayselections)
  }

  getDisplaySelections(): void {
    this.frontRepoService.pull(this.GONG__StackPath).subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        this.displayselections = this.frontRepo.DisplaySelections_array;

        // insertion point for time duration Recoveries
        // insertion point for enum int Recoveries

        // in case the component is called as a selection component
        if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {
          for (let displayselection of this.displayselections) {
            let ID = this.dialogData.ID
            let revPointer = displayselection[this.dialogData.ReversePointer as keyof DisplaySelectionDB] as unknown as NullInt64
            if (revPointer.Int64 == ID) {
              this.initialSelection.push(displayselection)
            }
            this.selection = new SelectionModel<DisplaySelectionDB>(allowMultiSelect, this.initialSelection);
          }
        }

        if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

          let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, DisplaySelectionDB>
          let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

          // we associates on sourceInstance of type SourceStruct with a MANY MANY associations to DisplaySelectionDB
          // the field name is sourceField
          let sourceFieldArray = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]! as unknown as DisplaySelectionDB[]
          if (sourceFieldArray != null) {
            for (let associationInstance of sourceFieldArray) {
              let displayselection = associationInstance[this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as DisplaySelectionDB
              this.initialSelection.push(displayselection)
            }
          }

          this.selection = new SelectionModel<DisplaySelectionDB>(allowMultiSelect, this.initialSelection);
        }

        // update the mat table data source
        this.matTableDataSource.data = this.displayselections
      }
    )
  }

  // newDisplaySelection initiate a new displayselection
  // create a new DisplaySelection objet
  newDisplaySelection() {
  }

  deleteDisplaySelection(displayselectionID: number, displayselection: DisplaySelectionDB) {
    // list of displayselections is truncated of displayselection before the delete
    this.displayselections = this.displayselections.filter(h => h !== displayselection);

    this.displayselectionService.deleteDisplaySelection(displayselectionID, this.GONG__StackPath).subscribe(
      displayselection => {
        this.displayselectionService.DisplaySelectionServiceChanged.next("delete")
      }
    );
  }

  editDisplaySelection(displayselectionID: number, displayselection: DisplaySelectionDB) {

  }

  // display displayselection in router
  displayDisplaySelectionInRouter(displayselectionID: number) {
    this.router.navigate(["github_com_fullstack_lang_gongxlsx_go-" + "displayselection-display", displayselectionID])
  }

  // set editor outlet
  setEditorRouterOutlet(displayselectionID: number) {
    this.router.navigate([{
      outlets: {
        github_com_fullstack_lang_gongxlsx_go_editor: ["github_com_fullstack_lang_gongxlsx_go-" + "displayselection-detail", displayselectionID, this.GONG__StackPath]
      }
    }]);
  }

  /** Whether the number of selected elements matches the total number of rows. */
  isAllSelected() {
    const numSelected = this.selection.selected.length;
    const numRows = this.displayselections.length;
    return numSelected === numRows;
  }

  /** Selects all rows if they are not all selected; otherwise clear selection. */
  masterToggle() {
    this.isAllSelected() ?
      this.selection.clear() :
      this.displayselections.forEach(row => this.selection.select(row));
  }

  save() {

    if (this.mode == TableComponentMode.ONE_MANY_ASSOCIATION_MODE) {

      let toUpdate = new Set<DisplaySelectionDB>()

      // reset all initial selection of displayselection that belong to displayselection
      for (let displayselection of this.initialSelection) {
        let index = displayselection[this.dialogData.ReversePointer as keyof DisplaySelectionDB] as unknown as NullInt64
        index.Int64 = 0
        index.Valid = true
        toUpdate.add(displayselection)

      }

      // from selection, set displayselection that belong to displayselection
      for (let displayselection of this.selection.selected) {
        let ID = this.dialogData.ID as number
        let reversePointer = displayselection[this.dialogData.ReversePointer as keyof DisplaySelectionDB] as unknown as NullInt64
        reversePointer.Int64 = ID
        reversePointer.Valid = true
        toUpdate.add(displayselection)
      }


      // update all displayselection (only update selection & initial selection)
      for (let displayselection of toUpdate) {
        this.displayselectionService.updateDisplaySelection(displayselection, this.GONG__StackPath)
          .subscribe(displayselection => {
            this.displayselectionService.DisplaySelectionServiceChanged.next("update")
          });
      }
    }

    if (this.mode == TableComponentMode.MANY_MANY_ASSOCIATION_MODE) {

      // get the source instance via the map of instances in the front repo
      let mapOfSourceInstances = this.frontRepo[this.dialogData.SourceStruct + "s" as keyof FrontRepo] as Map<number, DisplaySelectionDB>
      let sourceInstance = mapOfSourceInstances.get(this.dialogData.ID)!

      // First, parse all instance of the association struct and remove the instance
      // that have unselect
      let unselectedDisplaySelection = new Set<number>()
      for (let displayselection of this.initialSelection) {
        if (this.selection.selected.includes(displayselection)) {
          // console.log("displayselection " + displayselection.Name + " is still selected")
        } else {
          console.log("displayselection " + displayselection.Name + " has been unselected")
          unselectedDisplaySelection.add(displayselection.ID)
          console.log("is unselected " + unselectedDisplaySelection.has(displayselection.ID))
        }
      }

      // delete the association instance
      let associationInstance = sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]
      let displayselection = associationInstance![this.dialogData.IntermediateStructField as keyof typeof associationInstance] as unknown as DisplaySelectionDB
      if (unselectedDisplaySelection.has(displayselection.ID)) {
        this.frontRepoService.deleteService(this.dialogData.IntermediateStruct, associationInstance)


      }

      // is the source array is empty create it
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] == undefined) {
        (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance] as unknown as Array<DisplaySelectionDB>) = new Array<DisplaySelectionDB>()
      }

      // second, parse all instance of the selected
      if (sourceInstance[this.dialogData.SourceField as keyof typeof sourceInstance]) {
        this.selection.selected.forEach(
          displayselection => {
            if (!this.initialSelection.includes(displayselection)) {
              // console.log("displayselection " + displayselection.Name + " has been added to the selection")

              let associationInstance = {
                Name: sourceInstance["Name"] + "-" + displayselection.Name,
              }

              let index = associationInstance[this.dialogData.IntermediateStructField + "ID" as keyof typeof associationInstance] as unknown as NullInt64
              index.Int64 = displayselection.ID
              index.Valid = true

              let indexDB = associationInstance[this.dialogData.IntermediateStructField + "DBID" as keyof typeof associationInstance] as unknown as NullInt64
              indexDB.Int64 = displayselection.ID
              index.Valid = true

              this.frontRepoService.postService(this.dialogData.IntermediateStruct, associationInstance)

            } else {
              // console.log("displayselection " + displayselection.Name + " is still selected")
            }
          }
        )
      }

      // this.selection = new SelectionModel<DisplaySelectionDB>(allowMultiSelect, this.initialSelection);
    }

    // why pizza ?
    this.dialogRef.close('Pizza!');
  }
}
