// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { XLCellDB } from './xlcell-db'
import { XLCell, CopyXLCellToXLCellDB } from './xlcell'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports

@Injectable({
  providedIn: 'root'
})
export class XLCellService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  XLCellServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private xlcellsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.xlcellsUrl = origin + '/api/github.com/fullstack-lang/gongxlsx/go/v1/xlcells';
  }

  /** GET xlcells from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB[]> {
    return this.getXLCells(GONG__StackPath, frontRepo)
  }
  getXLCells(GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<XLCellDB[]>(this.xlcellsUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<XLCellDB[]>('getXLCells', []))
      );
  }

  /** GET xlcell by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB> {
    return this.getXLCell(id, GONG__StackPath, frontRepo)
  }
  getXLCell(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.xlcellsUrl}/${id}`;
    return this.http.get<XLCellDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched xlcell id=${id}`)),
      catchError(this.handleError<XLCellDB>(`getXLCell id=${id}`))
    );
  }

  // postFront copy xlcell to a version with encoded pointers and post to the back
  postFront(xlcell: XLCell, GONG__StackPath: string): Observable<XLCellDB> {
    let xlcellDB = new XLCellDB
    CopyXLCellToXLCellDB(xlcell, xlcellDB)
    const id = typeof xlcellDB === 'number' ? xlcellDB : xlcellDB.ID
    const url = `${this.xlcellsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<XLCellDB>(url, xlcellDB, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<XLCellDB>('postXLCell'))
    );
  }
  
  /** POST: add a new xlcell to the server */
  post(xlcelldb: XLCellDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB> {
    return this.postXLCell(xlcelldb, GONG__StackPath, frontRepo)
  }
  postXLCell(xlcelldb: XLCellDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<XLCellDB>(this.xlcellsUrl, xlcelldb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted xlcelldb id=${xlcelldb.ID}`)
      }),
      catchError(this.handleError<XLCellDB>('postXLCell'))
    );
  }

  /** DELETE: delete the xlcelldb from the server */
  delete(xlcelldb: XLCellDB | number, GONG__StackPath: string): Observable<XLCellDB> {
    return this.deleteXLCell(xlcelldb, GONG__StackPath)
  }
  deleteXLCell(xlcelldb: XLCellDB | number, GONG__StackPath: string): Observable<XLCellDB> {
    const id = typeof xlcelldb === 'number' ? xlcelldb : xlcelldb.ID;
    const url = `${this.xlcellsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<XLCellDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted xlcelldb id=${id}`)),
      catchError(this.handleError<XLCellDB>('deleteXLCell'))
    );
  }

  // updateFront copy xlcell to a version with encoded pointers and update to the back
  updateFront(xlcell: XLCell, GONG__StackPath: string): Observable<XLCellDB> {
    let xlcellDB = new XLCellDB
    CopyXLCellToXLCellDB(xlcell, xlcellDB)
    const id = typeof xlcellDB === 'number' ? xlcellDB : xlcellDB.ID
    const url = `${this.xlcellsUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<XLCellDB>(url, xlcellDB, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<XLCellDB>('updateXLCell'))
    );
  }

  /** PUT: update the xlcelldb on the server */
  update(xlcelldb: XLCellDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB> {
    return this.updateXLCell(xlcelldb, GONG__StackPath, frontRepo)
  }
  updateXLCell(xlcelldb: XLCellDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLCellDB> {
    const id = typeof xlcelldb === 'number' ? xlcelldb : xlcelldb.ID;
    const url = `${this.xlcellsUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<XLCellDB>(url, xlcelldb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated xlcelldb id=${xlcelldb.ID}`)
      }),
      catchError(this.handleError<XLCellDB>('updateXLCell'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in XLCellService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("XLCellService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
