// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpClientModule, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { XLRowDB } from './xlrow-db';
import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { XLCellDB } from './xlcell-db'

@Injectable({
  providedIn: 'root'
})
export class XLRowService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  XLRowServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private xlrowsUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.xlrowsUrl = origin + '/api/github.com/fullstack-lang/gongxlsx/go/v1/xlrows';
  }

  /** GET xlrows from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB[]> {
    return this.getXLRows(GONG__StackPath, frontRepo)
  }
  getXLRows(GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<XLRowDB[]>(this.xlrowsUrl, { params: params })
      .pipe(
        tap(),
		// tap(_ => this.log('fetched xlrows')),
        catchError(this.handleError<XLRowDB[]>('getXLRows', []))
      );
  }

  /** GET xlrow by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB> {
    return this.getXLRow(id, GONG__StackPath, frontRepo)
  }
  getXLRow(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.xlrowsUrl}/${id}`;
    return this.http.get<XLRowDB>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched xlrow id=${id}`)),
      catchError(this.handleError<XLRowDB>(`getXLRow id=${id}`))
    );
  }

  /** POST: add a new xlrow to the server */
  post(xlrowdb: XLRowDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB> {
    return this.postXLRow(xlrowdb, GONG__StackPath, frontRepo)
  }
  postXLRow(xlrowdb: XLRowDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB> {

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    for (let _xlcell of xlrowdb.Cells) {
      xlrowdb.XLRowPointersEncoding.Cells.push(_xlcell.ID)
    }
    xlrowdb.Cells = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<XLRowDB>(this.xlrowsUrl, xlrowdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        xlrowdb.Cells = new Array<XLCellDB>()
        for (let _id of xlrowdb.XLRowPointersEncoding.Cells) {
          let _xlcell = frontRepo.XLCells.get(_id)
          if (_xlcell != undefined) {
            xlrowdb.Cells.push(_xlcell!)
          }
        }
        // this.log(`posted xlrowdb id=${xlrowdb.ID}`)
      }),
      catchError(this.handleError<XLRowDB>('postXLRow'))
    );
  }

  /** DELETE: delete the xlrowdb from the server */
  delete(xlrowdb: XLRowDB | number, GONG__StackPath: string): Observable<XLRowDB> {
    return this.deleteXLRow(xlrowdb, GONG__StackPath)
  }
  deleteXLRow(xlrowdb: XLRowDB | number, GONG__StackPath: string): Observable<XLRowDB> {
    const id = typeof xlrowdb === 'number' ? xlrowdb : xlrowdb.ID;
    const url = `${this.xlrowsUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<XLRowDB>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted xlrowdb id=${id}`)),
      catchError(this.handleError<XLRowDB>('deleteXLRow'))
    );
  }

  /** PUT: update the xlrowdb on the server */
  update(xlrowdb: XLRowDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB> {
    return this.updateXLRow(xlrowdb, GONG__StackPath, frontRepo)
  }
  updateXLRow(xlrowdb: XLRowDB, GONG__StackPath: string, frontRepo: FrontRepo): Observable<XLRowDB> {
    const id = typeof xlrowdb === 'number' ? xlrowdb : xlrowdb.ID;
    const url = `${this.xlrowsUrl}/${id}`;

    // insertion point for reset of pointers (to avoid circular JSON)
	// and encoding of pointers
    for (let _xlcell of xlrowdb.Cells) {
      xlrowdb.XLRowPointersEncoding.Cells.push(_xlcell.ID)
    }
    xlrowdb.Cells = []

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<XLRowDB>(url, xlrowdb, httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        xlrowdb.Cells = new Array<XLCellDB>()
        for (let _id of xlrowdb.XLRowPointersEncoding.Cells) {
          let _xlcell = frontRepo.XLCells.get(_id)
          if (_xlcell != undefined) {
            xlrowdb.Cells.push(_xlcell!)
          }
        }
        // this.log(`updated xlrowdb id=${xlrowdb.ID}`)
      }),
      catchError(this.handleError<XLRowDB>('updateXLRow'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in XLRowService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("XLRowService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
