// generated by MultiCodeGeneratorNgService
import { Injectable } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs';
import { Observable, of } from 'rxjs';
import { catchError, map, tap } from 'rxjs/operators';

import { XLSheetDB } from './xlsheet-db';

@Injectable({
  providedIn: 'root'
})
export class XLSheetService {

  httpOptions = {
    headers: new HttpHeaders({ 'Content-Type': 'application/json' })
  };

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  XLSheetServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private xlsheetsUrl = 'http://localhost:8080/api/github.com/fullstack-lang/gongxlsx/go/v1/xlsheets';

  constructor(
    private http: HttpClient
  ) { }

  /** GET xlsheets from the server */
  getXLSheets(): Observable<XLSheetDB[]> {
    return this.http.get<XLSheetDB[]>(this.xlsheetsUrl)
      .pipe(
        tap(_ => this.log('fetched xlsheets')),
        catchError(this.handleError<XLSheetDB[]>('getXLSheets', []))
      );
  }

  /** GET xlsheet by id. Will 404 if id not found */
  getXLSheet(id: number): Observable<XLSheetDB> {
    const url = `${this.xlsheetsUrl}/${id}`;
    return this.http.get<XLSheetDB>(url).pipe(
      tap(_ => this.log(`fetched xlsheet id=${id}`)),
      catchError(this.handleError<XLSheetDB>(`getXLSheet id=${id}`))
    );
  }

  //////// Save methods //////////

  /** POST: add a new xlsheet to the server */
  postXLSheet(xlsheetdb: XLSheetDB): Observable<XLSheetDB> {

		// insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    xlsheetdb.Rows = []
    xlsheetdb.SheetCells = []
    let _XLFile_Sheets_reverse = xlsheetdb.XLFile_Sheets_reverse
    xlsheetdb.XLFile_Sheets_reverse = {}

		return this.http.post<XLSheetDB>(this.xlsheetsUrl, xlsheetdb, this.httpOptions).pipe(
			tap(_ => {
				// insertion point for restoration of reverse pointers
        xlsheetdb.XLFile_Sheets_reverse = _XLFile_Sheets_reverse
				this.log(`posted xlsheetdb id=${xlsheetdb.ID}`)
			}),
			catchError(this.handleError<XLSheetDB>('postXLSheet'))
		);
  }

  /** DELETE: delete the xlsheetdb from the server */
  deleteXLSheet(xlsheetdb: XLSheetDB | number): Observable<XLSheetDB> {
    const id = typeof xlsheetdb === 'number' ? xlsheetdb : xlsheetdb.ID;
    const url = `${this.xlsheetsUrl}/${id}`;

    return this.http.delete<XLSheetDB>(url, this.httpOptions).pipe(
      tap(_ => this.log(`deleted xlsheetdb id=${id}`)),
      catchError(this.handleError<XLSheetDB>('deleteXLSheet'))
    );
  }

  /** PUT: update the xlsheetdb on the server */
  updateXLSheet(xlsheetdb: XLSheetDB): Observable<XLSheetDB> {
    const id = typeof xlsheetdb === 'number' ? xlsheetdb : xlsheetdb.ID;
    const url = `${this.xlsheetsUrl}/${id}`;

    // insertion point for reset of pointers and reverse pointers (to avoid circular JSON)
    xlsheetdb.Rows = []
    xlsheetdb.SheetCells = []
    let _XLFile_Sheets_reverse = xlsheetdb.XLFile_Sheets_reverse
    xlsheetdb.XLFile_Sheets_reverse = {}

    return this.http.put(url, xlsheetdb, this.httpOptions).pipe(
      tap(_ => {
        // insertion point for restoration of reverse pointers
        xlsheetdb.XLFile_Sheets_reverse = _XLFile_Sheets_reverse
        this.log(`updated xlsheetdb id=${xlsheetdb.ID}`)
      }),
      catchError(this.handleError<XLSheetDB>('updateXLSheet'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error(error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {

  }
}
