// generated by gong
import { Component, OnInit, Inject, Optional } from '@angular/core';
import { TypeofExpr } from '@angular/compiler';
import { CdkDragDrop, moveItemInArray } from '@angular/cdk/drag-drop';

import { MatDialogRef, MAT_DIALOG_DATA, MatDialog } from '@angular/material/dialog'
import { DialogData } from '../front-repo.service'
import { SelectionModel } from '@angular/cdk/collections';

import { Router, RouterState } from '@angular/router';
import { DisplaySelectionDB } from '../displayselection-db'
import { DisplaySelectionService } from '../displayselection.service'

import { FrontRepoService, FrontRepo } from '../front-repo.service'
import { NullInt64 } from '../null-int64'

@Component({
  selector: 'lib-displayselection-sorting',
  templateUrl: './displayselection-sorting.component.html',
  styleUrls: ['./displayselection-sorting.component.css']
})
export class DisplaySelectionSortingComponent implements OnInit {

  frontRepo: FrontRepo = new (FrontRepo)

  // array of DisplaySelection instances that are in the association
  associatedDisplaySelections = new Array<DisplaySelectionDB>();

  constructor(
    private displayselectionService: DisplaySelectionService,
    private frontRepoService: FrontRepoService,

    // not null if the component is called as a selection component of displayselection instances
    public dialogRef: MatDialogRef<DisplaySelectionSortingComponent>,
    @Optional() @Inject(MAT_DIALOG_DATA) public dialogData: DialogData,

    private router: Router,
  ) {
    this.router.routeReuseStrategy.shouldReuseRoute = function () {
      return false;
    };
  }

  ngOnInit(): void {
    this.getDisplaySelections()
  }

  getDisplaySelections(): void {
    this.frontRepoService.pull().subscribe(
      frontRepo => {
        this.frontRepo = frontRepo

        let index = 0
        for (let displayselection of this.frontRepo.DisplaySelections_array) {
          let ID = this.dialogData.ID
          let revPointerID = displayselection[this.dialogData.ReversePointer as keyof DisplaySelectionDB] as unknown as NullInt64
          let revPointerID_Index = displayselection[this.dialogData.ReversePointer + "_Index" as keyof DisplaySelectionDB] as unknown as NullInt64
          if (revPointerID.Int64 == ID) {
            if (revPointerID_Index == undefined) {
              revPointerID_Index = new NullInt64
              revPointerID_Index.Valid = true
              revPointerID_Index.Int64 = index++
            }
            this.associatedDisplaySelections.push(displayselection)
          }
        }

        // sort associated displayselection according to order
        this.associatedDisplaySelections.sort((t1, t2) => {
          let t1_revPointerID_Index = t1[this.dialogData.ReversePointer + "_Index" as keyof typeof t1] as unknown as NullInt64
          let t2_revPointerID_Index = t2[this.dialogData.ReversePointer + "_Index" as keyof typeof t2] as unknown as NullInt64
          if (t1_revPointerID_Index && t2_revPointerID_Index) {
            if (t1_revPointerID_Index.Int64 > t2_revPointerID_Index.Int64) {
              return 1;
            }
            if (t1_revPointerID_Index.Int64 < t2_revPointerID_Index.Int64) {
              return -1;
            }
          }
          return 0;
        });
      }
    )
  }

  drop(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.associatedDisplaySelections, event.previousIndex, event.currentIndex);

    // set the order of DisplaySelection instances
    let index = 0

    for (let displayselection of this.associatedDisplaySelections) {
      let revPointerID_Index = displayselection[this.dialogData.ReversePointer + "_Index" as keyof DisplaySelectionDB] as unknown as NullInt64
      revPointerID_Index.Valid = true
      revPointerID_Index.Int64 = index++
    }
  }

  save() {

    this.associatedDisplaySelections.forEach(
      displayselection => {
        this.displayselectionService.updateDisplaySelection(displayselection)
          .subscribe(displayselection => {
            this.displayselectionService.DisplaySelectionServiceChanged.next("update")
          });
      }
    )

    this.dialogRef.close('Sorting of ' + this.dialogData.ReversePointer +' done');
  }
}
